### PR TITLE
chore: add some typescript definitions

### PR DESCRIPTION
**Pull request by colenso**
I've added some typescript definitions of the regexs that are exported.

### CODE REVIEW

**Comment by colenso** [comment]
To use these regex(s) one needs to add this to their `tsconfig.json` file:
```
"paths": {
    "ember-cli-app-version/*": [
       "node_modules/ember-cli-app-version"
     ],
}
```

**Comment by bertdeblock** [comment]
This makes TS think you can import these from the root which is not correct, as they are located in `addon/utils/regexp.js` and not `addon/index.js`. Also, I would consider these private API and not import them in to your app.

**Comment by bertdeblock** [comment]
I'm going to close this for now.
These regular expressions are only an implementation detail and should not be imported/used directly.

**Comment by colenso** [comment]
> I'm going to close this for now. These regular expressions are only an implementation detail and should not be imported/used directly.

Understood. Thanks for the quick feedback.

**Pull request closed without merging**
