### PR TITLE
fix: unrelated commits update app.js fingerprint

### PR DESCRIPTION
**Pull request by rpemberton**
### Problem
This addon stores the version in the app.js asset. And when including a git sha in the version, this causes the fingerprint of that asset to change on every commit even when there are no real code changes.

This means that users will always need to download app.js after every deploy, instead of being served a cached version when there aren't any changes.

### Solution
Store the version somewhere that doesn't end up in app.js

### CODE REVIEW

**Comment by rpemberton** [comment]
The ember-beta and ember-canary tests are failing, but also appear to be failing on master branch when I run them locally

>To use these addons, your app needs ember-auto-import >= 2: ember-source

**Comment by NullVoxPopuli** [comment]
Hi @rpemberton !

Any chance you'd also be willing to migrate the CI of this repo to github actions, and get things working with ember release/beta/canary?

If not, i can find someone to do it <3
But ideally, we need ci green first.

Much thanks for your contribution, looks like a solid feature!

**Comment by rpemberton** [comment]
@NullVoxPopuli I just created #388 which updates this addon to the latest blueprints and consequently also migrates to github actions

**Comment by bertdeblock** [comment]
Might be better if this addon doesn't store the app name and version under `config.APP` anymore?
AFAICT, that would solve it as well (for everyone) and wouldn't require a new option.
It seems that everything under `config.APP` ends up in the JS bundle, but I don't think that's really needed in this case?

**Comment by rpemberton** [comment]
Anybody interested in reviewing this?

**Review by NullVoxPopuli — APPROVED** [review]
100% agree that this is a breaking change, but I think it's one worth making.

Thanks for doing this work, @rpemberton !!!

**Comment by bertdeblock** [comment]
The implementation suggested in this PR is definitely an improvement over the current implementation, though I'm slightly worried about the churn this might cause for apps and addons that have come to rely on `config.APP.version` (even though it's not considered public API, I think). Maybe I'm overly cautious though.

FWIW, I think it might be even better if you just construct the version number you need in `config/environment.js` yourself.

For example:

```js
// config/environment.js

const commitInfo = require('git-commit-info')();
const packageFile = require('../package.json');

const ENV = {
  appVersion: {
    full: `${packageFile.version}+${commitInfo.shortHash}`,
    short: packageFile.version,
  },
};
```

Afterwards, you can just use `appVersion.full`, `appVersion.short`, or any other format where needed. Like this, all the work happens at build time and there would be no need in shipping any runtime code to display a version number. It would also avoid the issue this PR is trying to solve. I think this would also be my recommendation for people that want to include different info in their version numbers (for example, https://github.com/ember-cli/ember-cli-app-version/issues/49 and https://github.com/ember-cli/ember-cli-app-version/issues/50) than the info provided by this addon. Construct what you need in `config/environment.js` and use that directly.

**Comment by rpemberton** [comment]
My main concern is that this addon is included in the ember app blueprint, so if this addon is accidentally invalidating cache, that has far reaching effects.

**Comment by bertdeblock** [comment]
Yes, I understand the issue. I'm just unsure if it's worth pursuing this fix and introducing churn across the ecosystem / potentially breaking apps, when in the long run, it might be better to not use this addon at all. For example, under Embroider, it might be interesting / better to use something like https://www.npmjs.com/package/webpack-version-file-plugin or https://www.npmjs.com/package/vite-plugin-package-version. I guess I mainly feel uncomfortable making this decision. You could also reach out on Discord in `#dev-ember-cli` to see if anybody else has better view on this.

**Comment by rpemberton** [comment]
I also decided to remove it since it was very quick to replace with a DIY solution similar to what @bertdeblock suggested

**Pull request closed without merging**
